const expenseData = [
  {
    name: "Ibrahim",
    to: "Grocery Store",
    phoneNumber: 9876543210,
    expenses: 1500,
    description: "Bought groceries for the week",
  },
  {
    name: "Aadam",
    to: "Restaurant",
    phoneNumber: 9876543211,
    expenses: 1200,
    description: "Dinner with friends",
  },
  {
    name: "Abdul",
    to: "Petrol Station",
    phoneNumber: 9876543212,
    expenses: 800,
    description: "Filled fuel in the car",
  },
  {
    name: "Ibrahim",
    to: "Electronics Store",
    phoneNumber: 9876543210,
    expenses: 5000,
    description: "Bought headphones",
  },
  {
    name: "Aadam",
    to: "Book Store",
    phoneNumber: 9876543211,
    expenses: 400,
    description: "Purchased books for college",
  },
  {
    name: "Abdul",
    to: "Clothing Store",
    phoneNumber: 9876543212,
    expenses: 2500,
    description: "Bought clothes",
  },
  {
    name: "Ibrahim",
    to: "Gym",
    phoneNumber: 9876543210,
    expenses: 2000,
    description: "Monthly gym membership",
  },
  {
    name: "Aadam",
    to: "Coffee Shop",
    phoneNumber: 9876543211,
    expenses: 300,
    description: "Coffee with friends",
  },
  {
    name: "Abdul",
    to: "Stationery Store",
    phoneNumber: 9876543212,
    expenses: 700,
    description: "Bought stationery for work",
  },
  {
    name: "Ibrahim",
    to: "Pharmacy",
    phoneNumber: 9876543210,
    expenses: 150,
    description: "Purchased medicines",
  },
  {
    name: "Aadam",
    to: "Movie Theater",
    phoneNumber: 9876543211,
    expenses: 500,
    description: "Watched a movie",
  },
  {
    name: "Abdul",
    to: "Bakery",
    phoneNumber: 9876543212,
    expenses: 250,
    description: "Bought pastries",
  },
  {
    name: "Ibrahim",
    to: "Gas Station",
    phoneNumber: 9876543210,
    expenses: 900,
    description: "Fuel for the car",
  },
  {
    name: "Aadam",
    to: "Mobile Recharge",
    phoneNumber: 9876543211,
    expenses: 400,
    description: "Recharged mobile balance",
  },
  {
    name: "Abdul",
    to: "Music Store",
    phoneNumber: 9876543212,
    expenses: 600,
    description: "Bought music albums",
  },
  {
    name: "Ibrahim",
    to: "Hardware Store",
    phoneNumber: 9876543210,
    expenses: 800,
    description: "Bought tools for home",
  },
  {
    name: "Aadam",
    to: "Salon",
    phoneNumber: 9876543211,
    expenses: 1000,
    description: "Got a haircut",
  },
  {
    name: "Abdul",
    to: "Toy Store",
    phoneNumber: 9876543212,
    expenses: 300,
    description: "Bought toys for nephew",
  },
  {
    name: "Ibrahim",
    to: "Online Shopping",
    phoneNumber: 9876543210,
    expenses: 3500,
    description: "Ordered clothes online",
  },
  {
    name: "Aadam",
    to: "Laundry Service",
    phoneNumber: 9876543211,
    expenses: 500,
    description: "Paid for laundry services",
  },
  {
    name: "Abdul",
    to: "Park Entrance",
    phoneNumber: 9876543212,
    expenses: 100,
    description: "Paid entrance fee at park",
  },
  {
    name: "Ibrahim",
    to: "Food Delivery",
    phoneNumber: 9876543210,
    expenses: 1200,
    description: "Ordered pizza for dinner",
  },
  {
    name: "Aadam",
    to: "Library",
    phoneNumber: 9876543211,
    expenses: 250,
    description: "Renewed library membership",
  },
  {
    name: "Abdul",
    to: "Car Wash",
    phoneNumber: 9876543212,
    expenses: 400,
    description: "Paid for car wash",
  },
  {
    name: "Ibrahim",
    to: "Pet Store",
    phoneNumber: 9876543210,
    expenses: 700,
    description: "Bought food for pet",
  },
  {
    name: "Aadam",
    to: "Hospital",
    phoneNumber: 9876543211,
    expenses: 1800,
    description: "Doctor's consultation",
  },
  {
    name: "Abdul",
    to: "Gift Shop",
    phoneNumber: 9876543212,
    expenses: 600,
    description: "Bought gift for a friend",
  },
  {
    name: "Ibrahim",
    to: "Taxi",
    phoneNumber: 9876543210,
    expenses: 300,
    description: "Paid for taxi fare",
  },
  {
    name: "Aadam",
    to: "Spa",
    phoneNumber: 9876543211,
    expenses: 2000,
    description: "Relaxation spa session",
  },
  {
    name: "Abdul",
    to: "Furniture Store",
    phoneNumber: 9876543212,
    expenses: 1200,
    description: "Bought a new chair",
  },
  {
    name: "Ibrahim",
    to: "Flower Shop",
    phoneNumber: 9876543210,
    expenses: 250,
    description: "Bought flowers",
  },
  {
    name: "Aadam",
    to: "Beach",
    phoneNumber: 9876543211,
    expenses: 100,
    description: "Paid beach entrance fee",
  },
  {
    name: "Abdul",
    to: "Amusement Park",
    phoneNumber: 9876543212,
    expenses: 800,
    description: "Visited amusement park",
  },
  {
    name: "Ibrahim",
    to: "Bus Station",
    phoneNumber: 9876543210,
    expenses: 50,
    description: "Paid for bus fare",
  },
  {
    name: "Aadam",
    to: "Museum",
    phoneNumber: 9876543211,
    expenses: 150,
    description: "Museum entrance fee",
  },
  {
    name: "Abdul",
    to: "Photo Studio",
    phoneNumber: 9876543212,
    expenses: 300,
    description: "Passport photos",
  },
  {
    name: "Ibrahim",
    to: "Sport Store",
    phoneNumber: 9876543210,
    expenses: 1300,
    description: "Bought sports equipment",
  },
  {
    name: "Aadam",
    to: "Theater",
    phoneNumber: 9876543211,
    expenses: 400,
    description: "Watched a play",
  },
  {
    name: "Abdul",
    to: "Book Fair",
    phoneNumber: 9876543212,
    expenses: 500,
    description: "Purchased books",
  },
  {
    name: "Ibrahim",
    to: "Mall",
    phoneNumber: 9876543210,
    expenses: 3000,
    description: "Shopping spree",
  },
  {
    name: "Aadam",
    to: "Ice Cream Parlor",
    phoneNumber: 9876543211,
    expenses: 200,
    description: "Ice cream treat",
  },
  {
    name: "Abdul",
    to: "Pet Grooming",
    phoneNumber: 9876543212,
    expenses: 600,
    description: "Grooming for pet dog",
  },
  {
    name: "Ibrahim",
    to: "Public Transport",
    phoneNumber: 9876543210,
    expenses: 100,
    description: "Paid for train fare",
  },
  {
    name: "Aadam",
    to: "Bakery",
    phoneNumber: 9876543211,
    expenses: 150,
    description: "Bought pastries",
  },
  {
    name: "Abdul",
    to: "Pharmacy",
    phoneNumber: 9876543212,
    expenses: 300,
    description: "Bought vitamins",
  },
  {
    name: "Ibrahim",
    to: "Gift Shop",
    phoneNumber: 9876543210,
    expenses: 450,
    description: "Bought birthday gift",
  },
  {
    name: "Aadam",
    to: "Supermarket",
    phoneNumber: 9876543211,
    expenses: 2000,
    description: "Monthly grocery shopping",
  },
  {
    name: "Abdul",
    to: "Electronics Shop",
    phoneNumber: 9876543212,
    expenses: 7000,
    description: "Bought a new tablet",
  }
];

module.exports = { data: expenseData };
